manifest:
  remotes:
    - name: fouf96
      url-base: https://github.com/fouf96
  projects:
    - name: zmk
      remote: fouf96
      revision: main
      import: app/west.yml
  self:
    path: config
