manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      revision: v3.5-device-power-management
      import: app/west.yml
  self:
    path: config
